### PR TITLE
Translate to Portuguese

### PR DESCRIPTION
**Pull request by qgustavor**
Just "Link opens in a new tab." wasn't translated because it's not in the JSON file.

### CODE REVIEW

**Comment by Pizzacus** [comment]
Yeah, I ran it locally, it seems good!

Again, I am so sorry for forgetting to comment on the issue...

BTW, if you want, you can add your name to the footer with mine, I should've mentioned that... If you don't want to, just tell me and I'll merge this pull request!

**Comment by qgustavor** [comment]
~~Wait... I already commited it but I the wording is quite bad.~~ It was "A shitpost by ... and translated by ...", I fixed it to "A shitpost by... translated by...".

For some reason the edits weren't applied... git. You can squash the commits anyway...

**Comment by Pizzacus** [comment]
Thank you sooooo much and sorry again <3

**Comment by Pizzacus** [comment]
Okay, I rebuilt the gh-pages branch with your changes! You can check it out on the website! http://satania.moe/

**Pull request merged**
