### PR TITLE
Here's some ASCII art. Hope it still looks like Satania.

### PR DESCRIPTION
**Pull request by MagnificentPako**

### CODE REVIEW

**Comment by MagnificentPako** [comment]
Oh fuck, I misspelled her name because I was in a rush. Sorry! orz

**Comment by Pizzacus** [comment]
Looks more like gab than satania... idk what you think about it, but maybe another picture would be more recognisable

**Comment by Pizzacus** [comment]
Tho thanks for contributing! 👍 I am waaaay too lazy to do that ^_^

**Comment by MagnificentPako** [comment]
TBH, I didn't watch Gabriel Dropout (yet) so I wasn't sure how much of Satania was still in that art. Just stumbled upon this awesome page and saw that you wanted some ASCII art on there. I'll try to get some better art ASAP :)

**Comment by Pizzacus** [comment]
<3

**Comment by Pizzacus** [comment]
Ended up being done in #16, I'm closing this, thanks for trying anyway! ❤️

**Pull request closed without merging**
