### PR TITLE
Add the simplified Chinese language

### PR DESCRIPTION
**Pull request by copytime**
Dear Pizzacus:
Thanks for your web site. I am a Satania follower now.  LOL.
I added the simplified Chinese language.
And tested it in my local computer.
If there are any bugs.
You can email me  : zhou.yuxuan@outlook.com

### CODE REVIEW

**Comment by Pizzacus** [comment]
Thanks a lot for contributing ♥, that looks good except for one minor thing, the two-letter code of the locale.

We use codes that are compatible with the HTML `lang=""` attribute because this way we can tell the browser what language the page is in, this is a very relevant information for the browser, for page readers, dictionary lookups, and spell checking for websites where you can type things.

The code for Chinese in general is `zh`, but you can actually specify Simplified Chinese specifically with `zh-Hans` (according to [BCP47](https://tools.ietf.org/html/bcp47) which is the codes used for the HTML lang attribute)

So **TL;DR**, rename the locale file to `zh-Hans` (with an uppercase H) and change the \<select\>

EDIT: Also thanks to Netlify you can preview your pull request [here](https://deploy-preview-24--satania.netlify.com/) if you want, although you said you had already tested it on your computer so it should be fine

EDIT 2: Also you'll know that the locale name is good if it makes this date change to correct chinese
image

**Comment by copytime** [comment]
I made the change like you said.
It should be fine now. 

And the date message is in Chinese correctly at first(in the first version).
default

**Comment by Pizzacus** [comment]
Actually, the date depends on the language of the page, but if the language of the page is wrong, it uses the language of your computer so indeed you weren't able to tell ^-^ 

Anyway, that looks good so I'll merge this now, thanks a lot for contributing! It's really awesome to see there are so many satania followers around the world! >w<

Also recently we had a spike of Chinese users I have no idea what's up with that
image

**Comment by copytime** [comment]
## A large number of Chinese users have suddenly appeared recently?
I guess the reason is that a user has found the website and he shared this in [bilibili](https://www.bilibili.com/)(a Chinese website) .   
This is a website that looks like [Niconico](http://www.nicovideo.jp/) in Japen.  
default

Actually，I know your website by this message,too.   =￣ω￣=
## 50 users at the most time ? 
Well, maybe you don't know.   
We can't access some websites (such as Google,Facebook,Discord....) in China (the GFW).  
In fact, there are tons of anime fans in China. But we have to active in China only.  
Seldom of them could support or follow a website like yours. Sorry !

## Why copytime's English is so hard to understand ?
English is not my first language .....    😭
Sorry for the bad English ！
## Thank you again, **Pizzacus** !

**Comment by Pizzacus** [comment]
Yeah, actually, Google have specific domains for Google Analytics that aren't blocked in China, if they didn't they wouldn't be able to know we had users in China at all... Those domains being

 * google-analytics.com ([Not working in China](https://www.greatfirewallofchina.org/index.php?siteurl=google-analytics.com))
 * stats.g.doubleclick.net ([Working in China](https://www.greatfirewallofchina.org/index.php?siteurl=stats.g.doubleclick.net) and thus used instead)

The web interface allowing to see the stats is blocked though, as it is located on analytics.google.com

[We are even able to load our fonts from Google in China](https://www.greatfirewallofchina.org/index.php?siteurl=fonts.googleapis.com), although it only affects the English version, as serving Chinese fonts would be too much of a mess given the number of characters, [the icons are fine too](https://www.greatfirewallofchina.org/index.php?siteurl=materialdesignicons.com)

Although apparently [the domain satania.moe **itself** is blocked in China](https://www.greatfirewallofchina.org/index.php?siteurl=satania.moe), why? Well I think its because we use Netlify in order to host the website, I tried every other Netlify websites I could find, and those are also blocked as well

A workaround would be the fact that we own alternative domains, gabriel.moe, raphiel.moe and vignette.moe, those are not blocked as they are not hosted by Netlify, but they REDIRECT to satania.moe, so it still doesn't allow you to access the website, but maybe we could make them re-serve the page instead allowing us to provide users a way to bypass the block

**EDIT:** smug.satania.moe which we use to distribute some assets for the Satania bot on Discord is [NOT blocked in China](https://www.greatfirewallofchina.org/index.php?siteurl=smug.satania.moe), so we can actually just make a subdomain for Chinese users, that is way easier than another domain completely

**Comment by Pizzacus** [comment]
Also, I wanted to ask why there is a (?) there, did you forget to double-check this part? 
image

**Comment by copytime** [comment]
Wait! You did redirect the gabriel.moe, raphiel.moe and vignette.moe to satania.moe ?!!   
**LMAO !**
In fact I can access satania.moe freely without VPN. I guess lots of us could access your web page.  
I will ask my friends to check this out later.
But if they wants to join the Subreddit or Discord, they have to use VPN to bypass the block.
And not all of us could pay for the VPN.
## As for the (?) in the text
I leave it on purpose.
"人生目标" means "goals in life", but the word "人" means **"human"** in Chinese !
We all know satania is not a lowly human, right ? 😜
Just a small meme in Chinese language.   
Also I tranlated the "lmao" into "233". They are all the same reason. 
I think this will offer Chinese users a more native experience. 👍

**Comment by Pizzacus** [comment]
Actually, apparently, Discord works fine in China (but maybe some external technologies they use don't, so that would make it broken as well)

But I tried satania.moe in 3 different China Firewall check services and they all reported it as blocked

Setting up a domain for subdomain for Chinese users shouldn't be hard anyway, I'm currently seeing with Sebberino, the "tech guy" of Satania Dropout how that could work, I feel like its nice to offer ways for everyone to see the website, even if I guess it makes sense most people in China would know how to use VPNs and Tor

Also I don't know how I would name the domain, maybe `zanyang.satania.moe`? Apparently zànyáng / 赞扬 means "to praise" / "to glorify", so if "Zanyang Satania" makes sense we could use it to mean "praise.satania.moe"... We can't have actual Chinese characters or accents in domains, so that makes it tricky, I don't know if those words "work" when you write them like that

**Comment by copytime** [comment]
Discord works fine  in China of course.The hard thing is the robot verification.  
Who know it's based on google or something else.  
**IT JUST CAN'T VERIFY I AM A REAL MAN** without VPN.
You will never get this feeling unitl you come to China once...
   
Anyway I am still checking if we could connect to satania.moe directly.  
Will a new subdomain incress your server fee ?
If not, setting it up for Chinese user will be a wonderful thing.
And using PingYing, the "zanyang", is working. We could understand it.
But.......
No seriously, that's weird to me.  
I wonder if the subdomain can not be changed once been setted? 
If it is unchangeable, I will think twice and send you a better one in a few days.

**Comment by Pizzacus** [comment]
Oh yeah take your time we can change them it's very flexible

We COULD actually have Chinese characters in them via a thing called Punycode, which is basically if you name a domain in a very specific way, web browsers will pretend it was named another way, you can see that on <http://はじめよう.みんな>, which is actually http://xn--p8j9a0d9c9a.xn--q9jyb4c but web browsers pretend it's はじめよう.みんな

When Punycode domains became a thing, people were like "THIS IS THE THING OF THE FUTURE WE CAN HAVE FOREIGN CHARACTERS IN DOMAINS"

But it turns out it worked so weird that it never really took off, browsers would always be bad at pretending that the domains were encoded and many softwares supported them poorly, so you never see people getting domains with foreign characters in them

So **TL;DR** we can easily have a subdomain in actual Chinese but it might have unexpected behaviors in browsers

---------------------

Also, Discord use CloudFlare to check if you are human

And CloudFlare uses the Google Captcha system because it is the safest system out there it benefits
 * Users who get challenges that are easier for humans
 * Developers who get to have an extremely safe solution for Captchas
 * Google who get to use data for cool things apparently

But since it's Google, it is blocked in China, this is very sad and something that the Chinese government should reconsider, as it can actually benefit Chinese websites, since the Chinese Gov. unblocked certain Google services that are beneficial for Chinese websites (Google Analytics, Google Font, ...)  they should also unblock the Google Captcha

~~They should unblock satania.moe too~~

**Comment by copytime** [comment]
Punycode? Never heard before.
But that's a good news to me.  Since it cloud make browsers do something unexpectable. I will make two sets of plans. One in actual Chinese and the other in PingYing. You can test them in the feture.  

As for my test of accessing satania.moe. None of them were using VPN but they did accessed your website. I don't know why but your site is not been blocked.  I tried 3G/4G network, too. All of them are fine. No report of block in satania.moe. 

**WHY?**   Is there anything wrong with [greatfirewallofchina.org](https://www.greatfirewallofchina.org/index.php?siteurl=)?  
I don't know! I just can!  And I do live in China !!! (￣_￣)

********

One more thing.  I think this may be a good news to you. One of my friend said he can add a link to your site in his web page. 
This one : [toupros](http://toupros.com/).
Like this : 
default
Would you like to add your link to his website ?  
It's entirely up to you of course.

**Comment by Pizzacus** [comment]
Well, Okay IDK whats up with greatfirewallofchina.org, if it actually works then great :D 

But yeah I don't think I would add a link back to your friend's website, if he wants to share satania.moe then that's cool, but I am not actually looking into getting deals to cross-promote with other websites or anything, I hope you understand ^-^

I don't make any money from satania.moe and while I do own the Satania Dropout Discord server, it still doesn't make me feel the need to look for deals to promote it

**Comment by copytime** [comment]
Sorry for the late reply! I have to rest because of the time difference.  


I don't think I express it clearly.  My friend, he just wants to share your website.  And this is not some kind of business deals at all.  The last comment is requesting authorization to your website.  Adding a link without the owner's permission is rude.  
If you agreed, he could share your website without uneasiness.   
No charge at all, just a act of sharing         : )

**Comment by Pizzacus** [comment]
Oh, err, yea it is totally fine to share satania.moe wherever you want and people have been doing it a lot 

It is actually our main source of visitors, as web search engines (particularly Google) don't promote satania.moe a lot as it contains many keywords "hentai", "rule34", "/r/watchpeopledie", "foot-fetishism", which makes them believe that the website is very shady

And as such, it is hard to find satania.moe in search engines except if you really type specific things to find it specifically, so people sharing satania.moe is what we rely on to spread the word about Satania

Except Bing, for some reason, we are on the first page of Bing when you type "Satania"... yay?

Anyway, this thread is getting a bit long, if you have anything else to say or ask, you can do so on Discord at **Pizzacus#0061**, on Reddit at **/u/pizzacus** or by email via <pizzacus@gmail.com> ^-^

EDIT: Actually Google is the only one that filters satania.moe down, it is on the first page of DuckDuckGo, Yahoo, Bing and on the third page of Baidu, for comparison, satania.moe is on the 14th page of Google which is ridiculous

**Comment by Pizzacus** [comment]
Just thought one day I'd look into the Chinese language code

Because here are the codes we can use:
  * `zh-CN` -> Chinese from ~~China~~ [The People's Republic of China](https://user-images.githubusercontent.com/7659613/43968328-0f72b0fc-9cc7-11e8-9f14-89cb52c304e7.png)

  * `zh-Hans` -> Chinese in the Simplified Chinese script
  * `zh-cmn-Hans` -> Mandarin Chinese in the Simplified Chinese script

And I wanted to see which big Chinese websites use to decide which it should be on satania.moe

<details>
   <summary>List of tested websites <b>(click to reveal)</b></summary>

## `zh-CN`
  * [Google](https://www.google.com.hk/webhp?hl=zh-CN)
  * [QQ](http://www.qq.com/) | **Bonus point**: [QQ Music has a cool logo in their source code](https://user-images.githubusercontent.com/7659613/43966362-fb58cba6-9cc1-11e8-8810-a419788dd641.png) 
  * [JD.com](https://www.jd.com/)
  * [iQIYI](https://www.iqiyi.com/)
  * [芒果TV](http://www.mgtv.com/)
  * [Gaode Maps](https://ditu.amap.com/)


## `zh-Hans`
  * [BiliBili](https://www.bilibili.com/)

## `zh-cmn-Hans`
  * [Yinyue Tai](http://www.yinyuetai.com/)
  * [qunar.com](https://www.qunar.com/)

## Idiots who didn't set the language
  * **=>** [Baidu](https://www.baidu.com/) **<=**
  * [Weibo](https://www.weibo.com/)
  * [Microsoft Bing](http://cn.bing.com/) (They left it on English)
  * [Amazon China](https://www.amazon.cn/)
  * [Zhihu](https://www.zhihu.com/) (Doesn't specify the dialect)
  * [Sina](https://www.sina.com.cn/)
  * [NetEase / 163.com](https://www.163.com/)
  * [Sohu](http://www.sohu.com/)
  * [IFENG.com](http://www.ifeng.com/)
  * [Huangqiu.com](http://www.huanqiu.com/)
  * [The Paper](http://www.thepaper.cn/)
  * [Taobao](https://taobao.com/)
  * [YouKu](https://www.youku.com/)
  * [Xiami](https://www.xiami.com/)
  * [The Himalayas FM](https://www.ximalaya.com/)
  * [Dragonfly FM](http://www.qingting.fm/) (they set it to `""`)
  * [CTrip](https://www.ctrip.com/)
  * [AliTrip](https://www.alitrip.com/)
  * [Ma Feng Wo](http://www.mafengwo.cn/)
  * [QYER](http://www.qyer.com/)
  * [Dian Ping](http://www.dianping.com/) (They left it on English, surprizing for a Chinese company)
  * [Mei Tuan](https://www.meituan.com/)
  * [Xia Chufang](http://www.xiachufang.com/)
</details>

#### After looking into many websites, I decided I'll be renaming the translation to `zh-CN`

I'm actually reviewing many codes, Chinese is only one of them, **I'll also rename the Portuguese version from `pt` to `pt-PT`**, to distinguish it from the Brazilian dialect, which is pretty different, even if they are compatible, and **I'm looking if there are any other codes I could improve**

Languages are hard.

And I'll also make sure <https://satania.moe/#zh_Hans> redirects to <https//satania.moe/#zh-CN> for all the pre-existing links that exist.

So yeah, that's gonna happen soon, and since I tested many websites, I thought I would leave the list here for everyone to see. ^-^

**Pull request merged**
