### PR TITLE
Delete pt-PT.json

### PR DESCRIPTION
**Pull request by qgustavor**
Delete pt-PT translation.

### CODE REVIEW

**Comment by Pizzacus** [comment]
(ignore vercel its broken)

Hi, what's the problem with the pt-PT version? it the Brazilian one better?

Update: I removed Vercel, I was thinking of switching satania.moe from Netlify to Vercel a long time ago but gave up

**Comment by qgustavor** [comment]
Because it's pt-BR too and because I translated it and, even so, I think
mine is worse than the other pt-BR translation.

2021年1月13日(水) 15:21 Pizzacus™ <notifications@github.com>:

**Comment by Pizzacus** [comment]
Oh, okay. Well, if you think everyone's better off with the pt-BR version, it's probably better this way...

Still, I'm thankful for your contribution! I remember acting a bit mean in 2017, especially regarding the gender of "demon" when someone was telling me to change it, but I didn't mean to be mean D: ... I was a bit weird back then 🙏

**Comment by qgustavor** [comment]
I have no problem with the demon issue. In fact I find it funny: Crunchyroll used both genres! I asked they about that then they took *a whole month* to discuss what was the right choice. They ended choosing the male one then updated their subtitles. Anyway, it's almost impossible to make the pt-BR translation coherent with CR's: there it's "Satanya", not "Satania".

I hope someone makes a proper pt-PT translation. I watch a lot of anime in pt-PT, even so I still have a lot to learn about the language differences between countries.

**Pull request merged**
